### ISSUE TITLE
Send me an invite on Slack

### ISSUE THREAD

**Issue by TuxSeb** [chrobione/Jasper2fork#4]
Can you send me an invitation for the Jasper2Fork slack channel ? my email adress

se.rocca84@6m41l.c0m (leet speak)

**Comment by chrobione** [comment]
sorry i am screwing up the email address send it to chrobione@gmail.com

**Comment by chrobione** [comment]
try this dicord link:
https://discord.gg/d4bK4

**Comment by chrobione** [comment]
<iframe src="https://discordapp.com/widget?id=210109028460789761&theme=dark" width="350" height="500" allowtransparency="true" frameborder="0"></iframe>
